/**
 * jest.config.ts — Jest configuration for the Next.js frontend.
 *
 * `next/jest` wraps Jest with Next.js-specific transforms:
 * - Compiles TypeScript and JSX via the SWC compiler (fast).
 * - Mocks CSS imports, images, and next/font automatically.
 * - Loads .env files into process.env.
 *
 * Why we export an async function instead of calling createJestConfig(config):
 *
 * `next/jest` reads tsconfig.json paths and generates a moduleNameMapper entry
 * for `@/*` in **array form** (e.g. `["<rootDir>/$1"]`). Jest's `jest.mock()`
 * calls are hoisted before module resolution runs, and they fail to resolve
 * path aliases given in array form. We resolve the full next/jest config first,
 * then overwrite just the `@/` entry with the equivalent string form so both
 * regular imports and `jest.mock()` calls resolve correctly.
 */
import type { Config } from "jest";
import nextJest from "next/jest.js";

const createJestConfig = nextJest({ dir: "./" });

const config: Config = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  testPathIgnorePatterns: ["<rootDir>/node_modules/", "<rootDir>/.next/"],
  collectCoverageFrom: ["app/**/*.{ts,tsx}", "lib/**/*.{ts,tsx}", "!**/*.d.ts"],
};

const jestConfig = async () => {
  // Let next/jest build its full config (transforms, CSS mocks, etc.).
  const nextConfig = await createJestConfig(config)();

  return {
    ...nextConfig,
    moduleNameMapper: {
      // Preserve next/jest's other mappers (CSS modules, images, fonts…).
      ...nextConfig.moduleNameMapper,
      // Override the @/ entry with string form so jest.mock() hoisting works.
      // Array form (generated by next/jest from tsconfig paths) is not supported
      // by jest.mock() path resolution.
      "^@/(.*)$": "<rootDir>/$1",
    },
  };
};

export default jestConfig;
