# retrieval/retriever.py — Corpus retrieval with keyword, FAISS, and hybrid modes.
#
# Three concrete retrievers, all sharing the BaseRetriever interface:
#
#   KeywordRetriever  — BM25-lite scorer using TF normalised by √word_count.
#                       No dependencies beyond stdlib.  Always available.
#
#   FaissRetriever    — Cosine similarity via FAISS IndexFlatIP (unit vectors,
#                       so inner product == cosine similarity).  When a
#                       filter_topic is supplied it switches to a numpy dot-
#                       product over the filtered subset — this mirrors how
#                       production vector DBs (Pinecone namespaces, Weaviate
#                       classes) pre-filter before ANN search.
#
#   HybridRetriever   — Reciprocal Rank Fusion of both ranked lists.
#                       RRF score: Σ  1 / (k + rank_i),  k = 60 (standard).
#                       This is the default when embeddings are present because
#                       it consistently outperforms either signal alone on
#                       short, keyword-rich queries and longer semantic ones.
#
# Retriever selection (get_retriever):
#   embeddings present → HybridRetriever   retrieval_method = "hybrid-rrf"
#   no embeddings      → KeywordRetriever  retrieval_method = "bm25"
#
# Metadata filtering:
#   Every retrieve() call accepts filter_topic: Optional[str].
#   Passing a topic pre-filters the candidate set before scoring so only
#   chunks with that topic are eligible.  Callers use this to restrict
#   retrieval to species_activity, tide_basics, etc.

import json
import logging
import math
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Dict, List, Optional, Set

import numpy as np

logger = logging.getLogger(__name__)

_INDEX_PATH = Path(__file__).parent / "index.json"

# Standard RRF constant — reduces the impact of rank-1 dominance.
# k=60 is the value used in the original Cormack et al. 2009 paper.
_RRF_K = 60


# ── Stop words ────────────────────────────────────────────────────────────────

_STOP_WORDS: Set[str] = {
    "a", "an", "the", "and", "or", "but", "in", "on", "at", "to", "for",
    "of", "with", "by", "from", "is", "are", "was", "were", "be", "been",
    "being", "have", "has", "had", "do", "does", "did", "will", "would",
    "could", "should", "may", "might", "can", "that", "this", "these",
    "those", "it", "its", "as", "so", "if", "not", "no", "than", "then",
    "their", "they", "them", "there", "when", "where", "which", "who",
    "what", "how", "also", "up", "out", "into", "over", "after", "before",
    "very", "more", "most", "some", "any", "each", "both", "all", "other",
}


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class Chunk:
    """A retrievable piece of corpus text.

    embedding holds a pre-computed unit-normalised vector (all-MiniLM-L6-v2,
    384 dims) generated by scripts/build_index.py --embed.  None in keyword-
    only indexes.
    """

    chunk_id: str
    topic: str
    heading: str
    text: str
    word_count: int
    embedding: Optional[List[float]] = field(default=None, repr=False)

    def to_dict(self) -> dict:
        return {
            "chunk_id":   self.chunk_id,
            "topic":      self.topic,
            "heading":    self.heading,
            "text":       self.text,
            "word_count": self.word_count,
            "embedding":  self.embedding,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Chunk":
        return cls(
            chunk_id=data["chunk_id"],
            topic=data["topic"],
            heading=data["heading"],
            text=data["text"],
            word_count=data["word_count"],
            embedding=data.get("embedding"),
        )


# ── Shared interface ──────────────────────────────────────────────────────────

class BaseRetriever(ABC):
    """Common interface for all retriever implementations.

    filter_topic pre-restricts the candidate pool to a single corpus topic
    before any scoring occurs.  Passing None searches the full corpus.
    """

    @property
    @abstractmethod
    def retrieval_method(self) -> str:
        """Short label describing the retrieval strategy in use."""

    @abstractmethod
    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        filter_topic: Optional[str] = None,
    ) -> List[Chunk]:
        """Return up to top_k chunks most relevant to the query."""

    def retrieve_text(
        self,
        query: str,
        top_k: int = 3,
        filter_topic: Optional[str] = None,
    ) -> List[str]:
        """Convenience wrapper — returns only the text of each chunk."""
        return [c.text for c in self.retrieve(query, top_k=top_k, filter_topic=filter_topic)]


# ── Tokenisation (shared by keyword and hybrid) ───────────────────────────────

def tokenise(text: str) -> List[str]:
    """Lower-case, strip punctuation, remove stop words."""
    words = re.findall(r"[a-z]+", text.lower())
    return [w for w in words if w not in _STOP_WORDS and len(w) > 1]


# ── Keyword retriever ─────────────────────────────────────────────────────────

def _keyword_score(query_tokens: List[str], chunk: Chunk) -> float:
    """BM25-lite: TF normalised by √word_count, with phrase bonus."""
    if not query_tokens:
        return 0.0
    chunk_lower = chunk.text.lower()
    chunk_tokens = tokenise(chunk.text)
    tf_score = sum(chunk_tokens.count(t) for t in set(query_tokens))
    normalised = tf_score / max(1, math.sqrt(chunk.word_count))
    query_phrase = " ".join(query_tokens)
    phrase_bonus = 1.5 if len(query_tokens) >= 2 and query_phrase in chunk_lower else 1.0
    return normalised * phrase_bonus


class KeywordRetriever(BaseRetriever):
    """BM25-lite retriever — no external dependencies."""

    def __init__(self, chunks: List[Chunk]) -> None:
        self._chunks = chunks
        logger.info("KeywordRetriever ready | %d chunks", len(chunks))

    @property
    def retrieval_method(self) -> str:
        return "bm25"

    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        filter_topic: Optional[str] = None,
    ) -> List[Chunk]:
        active = _filter(self._chunks, filter_topic)
        query_tokens = tokenise(query)
        if not query_tokens:
            return []
        scored = [(c, _keyword_score(query_tokens, c)) for c in active]
        scored.sort(key=lambda x: x[1], reverse=True)
        return [c for c, s in scored[:top_k] if s > 0.0]


# ── FAISS retriever ───────────────────────────────────────────────────────────

class FaissRetriever(BaseRetriever):
    """Cosine-similarity retriever using an in-memory FAISS IndexFlatIP.

    Unfiltered queries use the pre-built FAISS index (O(N) ANN, scales to
    millions of vectors).  Metadata-filtered queries switch to an exact numpy
    dot-product over the filtered subset — this mirrors how production vector
    DBs pre-filter before ANN search and ensures only eligible chunks can win.
    """

    def __init__(self, chunks: List[Chunk], embedder: object) -> None:
        import faiss

        self._chunks = chunks
        self._embedder = embedder

        embeddings = np.array([c.embedding for c in chunks], dtype=np.float32)
        dim = embeddings.shape[1]
        self._index = faiss.IndexFlatIP(dim)
        self._index.add(embeddings)

        logger.info(
            "FaissRetriever ready | %d chunks | dim=%d (IndexFlatIP, cosine)",
            len(chunks), dim,
        )

    @property
    def retrieval_method(self) -> str:
        return "faiss"

    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        filter_topic: Optional[str] = None,
    ) -> List[Chunk]:
        query_vec = self._embedder.embed([query])  # shape (1, D)

        if filter_topic is not None:
            # ── Metadata-filtered path ─────────────────────────────────────
            # Build a score vector only for matching chunks, then sort.
            # This is exact (no approximation) and correct on any subset size.
            active = _filter(self._chunks, filter_topic)
            if not active:
                logger.debug("filter_topic=%r matched no chunks — searching all", filter_topic)
                active = self._chunks

            chunk_vecs = np.array([c.embedding for c in active], dtype=np.float32)
            scores = np.dot(chunk_vecs, query_vec[0])   # (N,) cosine similarity
            top_idx = np.argsort(scores)[::-1][:top_k]
            results = [active[i] for i in top_idx if scores[i] > 0.0]

            logger.debug(
                "FaissRetriever (filtered) | topic=%s | candidates=%d → top %d",
                filter_topic, len(active), len(results),
            )
            return results

        else:
            # ── Unfiltered path: use the pre-built FAISS index ─────────────
            k = min(top_k, len(self._chunks))
            faiss_scores, indices = self._index.search(query_vec, k)
            results = [
                self._chunks[idx]
                for idx, s in zip(indices[0], faiss_scores[0])
                if idx >= 0 and s > 0.0
            ]
            logger.debug(
                "FaissRetriever (full index) | top %d", len(results),
            )
            return results


# ── Hybrid retriever (BM25 + FAISS fused with RRF) ────────────────────────────

class HybridRetriever(BaseRetriever):
    """Combines keyword and semantic signals via Reciprocal Rank Fusion.

    RRF score for a document d:
        rrf(d) = Σ_i  1 / (k + rank_i(d))

    where rank_i is the document's position in ranked list i (0-based),
    and k = 60 (standard constant from Cormack et al. 2009).

    Why RRF over a weighted linear blend?
      - No tuning required: rank positions are scale-invariant.
      - Robust to score distribution mismatches between BM25 and cosine.
      - A document that appears in both lists is reliably ranked higher even
        if it isn't #1 in either — which is exactly what we want when the
        query has both keyword and semantic signals.
    """

    def __init__(self, chunks: List[Chunk], embedder: object) -> None:
        self._chunks = chunks
        self._keyword = KeywordRetriever(chunks)
        self._faiss   = FaissRetriever(chunks, embedder)
        self._chunk_map: Dict[str, Chunk] = {c.chunk_id: c for c in chunks}
        logger.info("HybridRetriever ready | BM25 + FAISS/RRF | k=%d", _RRF_K)

    @property
    def retrieval_method(self) -> str:
        return "hybrid-rrf"

    def retrieve(
        self,
        query: str,
        top_k: int = 3,
        filter_topic: Optional[str] = None,
    ) -> List[Chunk]:
        # Fetch full ranked lists from each signal (more than top_k so RRF has
        # enough material to fuse — cap at corpus size)
        n = len(self._chunks)
        kw_ranked = self._keyword.retrieve(query, top_k=n, filter_topic=filter_topic)
        fa_ranked = self._faiss.retrieve(query, top_k=n, filter_topic=filter_topic)

        # ── Reciprocal Rank Fusion ─────────────────────────────────────────
        rrf_scores: Dict[str, float] = {}
        for rank, chunk in enumerate(kw_ranked):
            rrf_scores[chunk.chunk_id] = (
                rrf_scores.get(chunk.chunk_id, 0.0) + 1.0 / (_RRF_K + rank + 1)
            )
        for rank, chunk in enumerate(fa_ranked):
            rrf_scores[chunk.chunk_id] = (
                rrf_scores.get(chunk.chunk_id, 0.0) + 1.0 / (_RRF_K + rank + 1)
            )

        sorted_ids = sorted(rrf_scores, key=lambda cid: rrf_scores[cid], reverse=True)
        results = [
            self._chunk_map[cid]
            for cid in sorted_ids[:top_k]
            if cid in self._chunk_map
        ]

        logger.debug(
            "HybridRetriever/RRF | query=%r | filter=%s | bm25=%d faiss=%d → top %d",
            query[:60], filter_topic, len(kw_ranked), len(fa_ranked), len(results),
        )
        return results


# ── Internal helpers ──────────────────────────────────────────────────────────

def _filter(chunks: List[Chunk], topic: Optional[str]) -> List[Chunk]:
    """Return chunks matching topic, or all chunks when topic is None."""
    if topic is None:
        return chunks
    return [c for c in chunks if c.topic == topic]


# ── Index loading ─────────────────────────────────────────────────────────────

def _load_index() -> List[Chunk]:
    if not _INDEX_PATH.exists():
        raise FileNotFoundError(
            f"Retrieval index not found at {_INDEX_PATH}. "
            "Run  python scripts/build_index.py --embed  to build it."
        )
    data = json.loads(_INDEX_PATH.read_text(encoding="utf-8"))
    chunks = [Chunk.from_dict(c) for c in data["chunks"]]
    has_embeddings = any(c.embedding is not None for c in chunks)
    logger.info(
        "Index loaded | version=%s | chunks=%d | embeddings=%s | built=%s",
        data.get("version", "?"),
        len(chunks),
        has_embeddings,
        data.get("built_at", "unknown"),
    )
    return chunks


@lru_cache(maxsize=None)
def get_retriever() -> BaseRetriever:
    """Return the best retriever for the current index.

    Decision:
      embeddings present → HybridRetriever (BM25 + FAISS, fused with RRF)
      no embeddings      → KeywordRetriever (BM25-lite, no model needed)

    lru_cache ensures the FAISS index is built exactly once per process.
    """
    chunks = _load_index()
    has_embeddings = any(c.embedding is not None for c in chunks)

    if has_embeddings:
        try:
            import faiss  # noqa: F401 — verify importable before constructing
            from app.retrieval.embedder import Embedder
            embedder = Embedder()
            retriever = HybridRetriever(chunks, embedder)
            logger.info("Active retriever: %s", retriever.retrieval_method)
            return retriever
        except ImportError as exc:
            logger.warning(
                "faiss/fastembed unavailable (%s) — falling back to keyword retrieval",
                exc,
            )

    retriever = KeywordRetriever(chunks)
    logger.info("Active retriever: %s", retriever.retrieval_method)
    return retriever
